#!/bin/bash -e

Q=$(dirname "$(readlink -f "$0")")
## "$Q/../ruby.local/bin/ruby" "$Q/zapusk.rb" $*

# this is important to run script using PATH modification
# this will allow sub-ruby scripts to start via /usr/bin/env
PATH="$Q/../ruby.local/bin:$PATH" "$Q/zapusk.rb" $*